import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const srcDir = resolve('src');
const scrapersDir = join(srcDir, 'scrapers');
const indexFile = join(srcDir, 'index.ts');

const rootFiles = await readdir(srcDir);
const sharedFiles = rootFiles
  .filter((file) => file.endsWith('.ts') && file !== 'index.ts')
  .sort((left, right) => left.localeCompare(right));

const scraperFiles = await readdir(scrapersDir).catch(() => [] as string[]);
const scraperExports = scraperFiles
  .filter((file) => file.endsWith('.ts') && file !== 'index.ts')
  .sort((left, right) => left.localeCompare(right));

const lines = [
  '// This file is generated by scripts/generate-exports.ts. Do not edit by hand.',
  ...sharedFiles.map((file) => {
    const name = file.replace(/\.ts$/, '');
    return `export * from './${name}';`;
  }),
  ...scraperExports.map((file) => {
    const name = file.replace(/\.ts$/, '');
    return `export * from './scrapers/${name}';`;
  }),
  '',
].join('\n');

await mkdir(srcDir, { recursive: true });
await writeFile(indexFile, lines, 'utf8');
